// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyFEl4iwLL9m7eBcKsRIuH-eEQT93Mn6s',
    appId: '1:672769898353:web:985e756ddcdd65c05b28d0',
    messagingSenderId: '672769898353',
    projectId: 'village-1727b',
    authDomain: 'village-1727b.firebaseapp.com',
    storageBucket: 'village-1727b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyFEl4iwLL9m7eBcKsRIuH-eEQT93Mn6s',
    appId: '1:672769898353:web:985e756ddcdd65c05b28d0',
    messagingSenderId: '672769898353',
    projectId: 'village-1727b',
    authDomain: 'village-1727b.firebaseapp.com',
    storageBucket: 'village-1727b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj3zqf8gRBkqeLCgqxQMDvDqVRDtPL0O0',
    appId: '1:672769898353:android:9ad26ddb779dac375b28d0',
    messagingSenderId: '672769898353',
    projectId: 'village-1727b',
    storageBucket: 'village-1727b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpeEaePuHuwKg0f0Oph8rkH5D-52zf4rI',
    appId: '1:1064035305311:ios:7f7065ad245a74f563d8ea',
    messagingSenderId: '672769898353',
    projectId: 'village-1727b',
    storageBucket: 'village-1727b.firebasestorage.app',
    iosBundleId: 'com.example.doulatpara',
  );

}