// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_YhdEw1MmyKQ-KJ18iwIB_ik9qvj28n4',
    appId: '1:1064035305311:web:46750e29f45ef90863d8ea',
    messagingSenderId: '1064035305311',
    projectId: 'village-1a6d9',
    authDomain: 'village-1a6d9.firebaseapp.com',
    storageBucket: 'village-1a6d9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_YhdEw1MmyKQ-KJ18iwIB_ik9qvj28n4',
    appId: '1:1064035305311:web:94b23aa6da6be03a63d8ea',
    messagingSenderId: '1064035305311',
    projectId: 'village-1a6d9',
    authDomain: 'village-1a6d9.firebaseapp.com',
    storageBucket: 'village-1a6d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_YhdEw1MmyKQ-KJ18iwIB_ik9qvj28n4',
    appId: '1:1064035305311:android:c10112206706a9fa63d8ea',
    messagingSenderId: '1064035305311',
    projectId: 'village-1a6d9',
    storageBucket: 'village-1a6d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_YhdEw1MmyKQ-KJ18iwIB_ik9qvj28n4',
    appId: '1:1064035305311:ios:7f7065ad245a74f563d8ea',
    messagingSenderId: '1064035305311',
    projectId: 'village-1a6d9',
    storageBucket: 'village-1a6d9.firebasestorage.app',
    iosBundleId: 'com.example.doulatpara',
  );

}
